[package]
name = "plhistr"
version = "0.1.1"
edition = "2021"
description = "Plot a histogram of a CSV column in the terminal"
license = "MIT"

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
csv = "1.4.0"
indicatif = "0.17"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"
